name: Bug Report
description: Report a bug in nepali-date-carbon
title: "[Bug]: "
labels: ["bug"]
body:
- type: markdown
  attributes:
  value: |
  Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
  label: What happened?
  description: Also tell us, what did you expect to happen?
  placeholder: Tell us what you see!
  validations:
  required: true
- type: input
  id: version
  attributes:
  label: Version
  description: What version of nepali-date-carbon are you using?
  placeholder: e.g., 0.2.0
  validations:
  required: true
- type: dropdown
  id: php-version
  attributes:
  label: PHP Version
  description: What version of PHP are you using?
  options:
  - PHP 8.2
  - PHP 8.1
  - PHP 8.0
  - Other (specify in additional context)
  validations:
  required: true
- type: dropdown
  id: laravel-version
  attributes:
  label: Laravel Version
  description: What version of Laravel are you using?
  options:
  - Laravel 12.x
  - Laravel 11.x
  - Laravel 10.x
  - Other (specify in additional context)
  validations:
  required: true
- type: textarea
  id: code-example
  attributes:
  label: Code Example
  description: Please provide a code example that demonstrates the issue
  render: php
- type: textarea
  id: additional-context
  attributes:
  label: Additional context
  description: Add any other context about the problem here
