blank_issues_enabled: false
contact_links:
  - name: Contact Me
    url: https://akashpoudel.com.np
    about: Ask the community for help with using Nepali Date Carbon
  - name: Report a security issue
    url: https://github.com/akashpoudelnp/nepali-date-carbon/security/policy
    about: Learn how to notify us for sensitive bugs
