name: Feature Request
description: Suggest a new feature for nepali-date-carbon
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Describe the feature you'd like to see added
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the problem this feature would solve
      placeholder: This feature would help when...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: If you have ideas about how this feature could be implemented, share them here
      placeholder: One way to implement this would be...
  - type: dropdown
    id: importance
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR to implement this feature
          required: false
